### ISSUE TITLE
If statement that doesn't do anything!

### ISSUE THREAD

**Issue by jmburges** [DoSomething/ios-RBReviewer#38]
https://github.com/DoSomething/ios-RBReviewer/blob/master/RBReviewer%2FDSODoSomethingAPIClient.m#L216-L217

**Comment by mshmsh5000** [comment]
:+1: @aaronschachter you're fired /cc @jmburges @jonuy

**Comment by mshmsh5000** [comment]
Welcome back to the team @aaronschachter
